default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: edu_active_api_development
test:
  <<: *default
  database: edu_active_api_test

production:
  url: <%= ENV['DATABASE_URL'] %>
